package azurerm

import "github.com/snyk/driftctl/enumeration/resource"

func InitResourcesMetadata(resourceSchemaRepository resource.SchemaRepositoryInterface) {
	initAzureNetworkSecurityGroupMetadata(resourceSchemaRepository)
	initAzurePrivateDNSZoneMetaData(resourceSchemaRepository)
	initAzurePrivateDNSARecordMetaData(resourceSchemaRepository)
	initAzurePrivateDNSAAAARecordMetaData(resourceSchemaRepository)
	initAzurePrivateDNSPTRRecordMetaData(resourceSchemaRepository)
	initAzurePrivateDNSSRVRecordMetaData(resourceSchemaRepository)
	initAzurePrivateDNSMXRecordMetaData(resourceSchemaRepository)
	initAzurePrivateDNSTXTRecordMetaData(resourceSchemaRepository)
	initAzureSSHPublicKeyMetaData(resourceSchemaRepository)
	initAzurePrivateDNSCNameRecordMetaData(resourceSchemaRepository)
	initAzureLoadBalancerRuleMetadata(resourceSchemaRepository)
}
