project_name: driftctl
dist: bin
release:
    github:
        owner: snyk
        name: driftctl
    draft: false
    prerelease: auto
before:
    hooks:
        - go generate ./...
signs:
    - signature: "${artifact}.gpg"
      artifacts: checksum
      args: [ "--batch", "-u", "team-cloud-config+security@snyk.io", "--output", "${signature}", "--detach-sign", "${artifact}" ]
builds:
    - id: "driftctl"
      binary: driftctl
      dir: .
      env:
          - CGO_ENABLED=0
      goos:
          - linux
          - windows
          - darwin
      goarch:
          - amd64
          - arm
          - arm64
          - 386
      ldflags: "-s -w -X github.com/snyk/driftctl/build.env={{ .Env.ENV }} -X github.com/snyk/driftctl/pkg/version.version={{ .Tag }}"
archives:
    - name_template: '{{ .ProjectName }}_{{ .Os }}_{{- if eq .Arch "armv6" }}arm{{- else }}{{ .Arch }}{{ end }}'
      format: binary
checksum:
    name_template: '{{ .ProjectName }}_SHA256SUMS'
    algorithm: sha256
snapshot:
    name_template: "{{ .Tag }}-next"
blobs:
    - provider: s3
      bucket: snyk-assets
      region: us-east-1
      folder: "cli/driftctl/{{.Tag}}"
