// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package common

import (
	resource "github.com/cloudskiff/driftctl/pkg/resource"
	mock "github.com/stretchr/testify/mock"
)

// MockEnumerator is an autogenerated mock type for the Enumerator type
type MockEnumerator struct {
	mock.Mock
}

// Enumerate provides a mock function with given fields:
func (_m *MockEnumerator) Enumerate() ([]*resource.Resource, error) {
	ret := _m.Called()

	var r0 []*resource.Resource
	if rf, ok := ret.Get(0).(func() []*resource.Resource); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*resource.Resource)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SupportedType provides a mock function with given fields:
func (_m *MockEnumerator) SupportedType() resource.ResourceType {
	ret := _m.Called()

	var r0 resource.ResourceType
	if rf, ok := ret.Get(0).(func() resource.ResourceType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(resource.ResourceType)
	}

	return r0
}
