// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package azure

import (
	context "context"

	armstorage "github.com/Azure/azure-sdk-for-go/sdk/storage/armstorage"

	mock "github.com/stretchr/testify/mock"
)

// MockListContainerItemPager is an autogenerated mock type for the ListContainerItemPager type
type MockListContainerItemPager struct {
	mock.Mock
}

// Err provides a mock function with given fields:
func (_m *MockListContainerItemPager) Err() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NextPage provides a mock function with given fields: _a0
func (_m *MockListContainerItemPager) NextPage(_a0 context.Context) bool {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// PageResponse provides a mock function with given fields:
func (_m *MockListContainerItemPager) PageResponse() armstorage.ListContainerItemsResponse {
	ret := _m.Called()

	var r0 armstorage.ListContainerItemsResponse
	if rf, ok := ret.Get(0).(func() armstorage.ListContainerItemsResponse); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(armstorage.ListContainerItemsResponse)
	}

	return r0
}
