// Code generated by mockery v2.3.0. DO NOT EDIT.

package github

import mock "github.com/stretchr/testify/mock"

// MockGithubRepository is an autogenerated mock type for the GithubRepository type
type MockGithubRepository struct {
	mock.Mock
}

// ListRepositories provides a mock function with given fields:
func (_m *MockGithubRepository) ListRepositories() ([]string, error) {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
