// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package repository

import (
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork"
	mock "github.com/stretchr/testify/mock"
)

// mockNetworkSecurityGroupsClient is an autogenerated mock type for the networkSecurityGroupsClient type
type mockNetworkSecurityGroupsClient struct {
	mock.Mock
}

// ListAll provides a mock function with given fields: options
func (_m *mockNetworkSecurityGroupsClient) ListAll(options *armnetwork.NetworkSecurityGroupsListAllOptions) networkSecurityGroupsListAllPager {
	ret := _m.Called(options)

	var r0 networkSecurityGroupsListAllPager
	if rf, ok := ret.Get(0).(func(*armnetwork.NetworkSecurityGroupsListAllOptions) networkSecurityGroupsListAllPager); ok {
		r0 = rf(options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(networkSecurityGroupsListAllPager)
		}
	}

	return r0
}
