// Code generated by mockery v2.28.1. DO NOT EDIT.

package repository

import (
	armnetwork "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork"
	mock "github.com/stretchr/testify/mock"
)

// mockPublicIPAddressesClient is an autogenerated mock type for the publicIPAddressesClient type
type mockPublicIPAddressesClient struct {
	mock.Mock
}

// ListAll provides a mock function with given fields: options
func (_m *mockPublicIPAddressesClient) ListAll(options *armnetwork.PublicIPAddressesListAllOptions) publicIPAddressesListAllPager {
	ret := _m.Called(options)

	var r0 publicIPAddressesListAllPager
	if rf, ok := ret.Get(0).(func(*armnetwork.PublicIPAddressesListAllOptions) publicIPAddressesListAllPager); ok {
		r0 = rf(options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(publicIPAddressesListAllPager)
		}
	}

	return r0
}

type mockConstructorTestingTnewMockPublicIPAddressesClient interface {
	mock.TestingT
	Cleanup(func())
}

// newMockPublicIPAddressesClient creates a new instance of mockPublicIPAddressesClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockPublicIPAddressesClient(t mockConstructorTestingTnewMockPublicIPAddressesClient) *mockPublicIPAddressesClient {
	mock := &mockPublicIPAddressesClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
