// Code generated by mockery v2.28.1. DO NOT EDIT.

package repository

import (
	armcontainerregistry "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerregistry/armcontainerregistry"
	mock "github.com/stretchr/testify/mock"
)

// mockRegistryClient is an autogenerated mock type for the registryClient type
type mockRegistryClient struct {
	mock.Mock
}

// List provides a mock function with given fields: options
func (_m *mockRegistryClient) List(options *armcontainerregistry.RegistriesListOptions) registryListAllPager {
	ret := _m.Called(options)

	var r0 registryListAllPager
	if rf, ok := ret.Get(0).(func(*armcontainerregistry.RegistriesListOptions) registryListAllPager); ok {
		r0 = rf(options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(registryListAllPager)
		}
	}

	return r0
}

type mockConstructorTestingTnewMockRegistryClient interface {
	mock.TestingT
	Cleanup(func())
}

// newMockRegistryClient creates a new instance of mockRegistryClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockRegistryClient(t mockConstructorTestingTnewMockRegistryClient) *mockRegistryClient {
	mock := &mockRegistryClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
