// Code generated by mockery v2.28.1. DO NOT EDIT.

package repository

import (
	armresources "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armresources"
	mock "github.com/stretchr/testify/mock"
)

// MockResourcesRepository is an autogenerated mock type for the ResourcesRepository type
type MockResourcesRepository struct {
	mock.Mock
}

// ListAllResourceGroups provides a mock function with given fields:
func (_m *MockResourcesRepository) ListAllResourceGroups() ([]*armresources.ResourceGroup, error) {
	ret := _m.Called()

	var r0 []*armresources.ResourceGroup
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*armresources.ResourceGroup, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*armresources.ResourceGroup); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*armresources.ResourceGroup)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockResourcesRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockResourcesRepository creates a new instance of MockResourcesRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockResourcesRepository(t mockConstructorTestingTNewMockResourcesRepository) *MockResourcesRepository {
	mock := &MockResourcesRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
