// Code generated by mockery v2.28.1. DO NOT EDIT.

package repository

import (
	context "context"

	armnetwork "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork"

	mock "github.com/stretchr/testify/mock"
)

// mockNetworkSecurityGroupsListAllPager is an autogenerated mock type for the networkSecurityGroupsListAllPager type
type mockNetworkSecurityGroupsListAllPager struct {
	mock.Mock
}

// Err provides a mock function with given fields:
func (_m *mockNetworkSecurityGroupsListAllPager) Err() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NextPage provides a mock function with given fields: ctx
func (_m *mockNetworkSecurityGroupsListAllPager) NextPage(ctx context.Context) bool {
	ret := _m.Called(ctx)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// PageResponse provides a mock function with given fields:
func (_m *mockNetworkSecurityGroupsListAllPager) PageResponse() armnetwork.NetworkSecurityGroupsListAllResponse {
	ret := _m.Called()

	var r0 armnetwork.NetworkSecurityGroupsListAllResponse
	if rf, ok := ret.Get(0).(func() armnetwork.NetworkSecurityGroupsListAllResponse); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(armnetwork.NetworkSecurityGroupsListAllResponse)
	}

	return r0
}

type mockConstructorTestingTnewMockNetworkSecurityGroupsListAllPager interface {
	mock.TestingT
	Cleanup(func())
}

// newMockNetworkSecurityGroupsListAllPager creates a new instance of mockNetworkSecurityGroupsListAllPager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockNetworkSecurityGroupsListAllPager(t mockConstructorTestingTnewMockNetworkSecurityGroupsListAllPager) *mockNetworkSecurityGroupsListAllPager {
	mock := &mockNetworkSecurityGroupsListAllPager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
