// Code generated by mockery v2.28.1. DO NOT EDIT.

package repository

import (
	context "context"

	armnetwork "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork"

	mock "github.com/stretchr/testify/mock"
)

// mockFirewallsListAllPager is an autogenerated mock type for the firewallsListAllPager type
type mockFirewallsListAllPager struct {
	mock.Mock
}

// Err provides a mock function with given fields:
func (_m *mockFirewallsListAllPager) Err() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NextPage provides a mock function with given fields: ctx
func (_m *mockFirewallsListAllPager) NextPage(ctx context.Context) bool {
	ret := _m.Called(ctx)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// PageResponse provides a mock function with given fields:
func (_m *mockFirewallsListAllPager) PageResponse() armnetwork.AzureFirewallsListAllResponse {
	ret := _m.Called()

	var r0 armnetwork.AzureFirewallsListAllResponse
	if rf, ok := ret.Get(0).(func() armnetwork.AzureFirewallsListAllResponse); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(armnetwork.AzureFirewallsListAllResponse)
	}

	return r0
}

type mockConstructorTestingTnewMockFirewallsListAllPager interface {
	mock.TestingT
	Cleanup(func())
}

// newMockFirewallsListAllPager creates a new instance of mockFirewallsListAllPager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockFirewallsListAllPager(t mockConstructorTestingTnewMockFirewallsListAllPager) *mockFirewallsListAllPager {
	mock := &mockFirewallsListAllPager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
