// Code generated by mockery v2.28.1. DO NOT EDIT.

package repository

import (
	armnetwork "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork"
	mock "github.com/stretchr/testify/mock"
)

// mockLoadBalancersClient is an autogenerated mock type for the loadBalancersClient type
type mockLoadBalancersClient struct {
	mock.Mock
}

// ListAll provides a mock function with given fields: options
func (_m *mockLoadBalancersClient) ListAll(options *armnetwork.LoadBalancersListAllOptions) loadBalancersListAllPager {
	ret := _m.Called(options)

	var r0 loadBalancersListAllPager
	if rf, ok := ret.Get(0).(func(*armnetwork.LoadBalancersListAllOptions) loadBalancersListAllPager); ok {
		r0 = rf(options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(loadBalancersListAllPager)
		}
	}

	return r0
}

type mockConstructorTestingTnewMockLoadBalancersClient interface {
	mock.TestingT
	Cleanup(func())
}

// newMockLoadBalancersClient creates a new instance of mockLoadBalancersClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockLoadBalancersClient(t mockConstructorTestingTnewMockLoadBalancersClient) *mockLoadBalancersClient {
	mock := &mockLoadBalancersClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
