// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package repository

import (
	armcompute "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute"
	mock "github.com/stretchr/testify/mock"
)

// mockImagesClient is an autogenerated mock type for the imagesClient type
type mockImagesClient struct {
	mock.Mock
}

// List provides a mock function with given fields: options
func (_m *mockImagesClient) List(options *armcompute.ImagesListOptions) imagesListPager {
	ret := _m.Called(options)

	var r0 imagesListPager
	if rf, ok := ret.Get(0).(func(*armcompute.ImagesListOptions) imagesListPager); ok {
		r0 = rf(options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(imagesListPager)
		}
	}

	return r0
}
