// Code generated by mockery v2.28.1. DO NOT EDIT.

package repository

import (
	armcompute "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute"
	mock "github.com/stretchr/testify/mock"
)

// mockSshPublicKeyClient is an autogenerated mock type for the sshPublicKeyClient type
type mockSshPublicKeyClient struct {
	mock.Mock
}

// ListBySubscription provides a mock function with given fields: options
func (_m *mockSshPublicKeyClient) ListBySubscription(options *armcompute.SSHPublicKeysListBySubscriptionOptions) sshPublicKeyListPager {
	ret := _m.Called(options)

	var r0 sshPublicKeyListPager
	if rf, ok := ret.Get(0).(func(*armcompute.SSHPublicKeysListBySubscriptionOptions) sshPublicKeyListPager); ok {
		r0 = rf(options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sshPublicKeyListPager)
		}
	}

	return r0
}

type mockConstructorTestingTnewMockSshPublicKeyClient interface {
	mock.TestingT
	Cleanup(func())
}

// newMockSshPublicKeyClient creates a new instance of mockSshPublicKeyClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockSshPublicKeyClient(t mockConstructorTestingTnewMockSshPublicKeyClient) *mockSshPublicKeyClient {
	mock := &mockSshPublicKeyClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
