// Code generated by mockery v2.28.1. DO NOT EDIT.

package repository

import (
	context "context"

	armstorage "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage"

	mock "github.com/stretchr/testify/mock"
)

// mockStorageAccountListPager is an autogenerated mock type for the storageAccountListPager type
type mockStorageAccountListPager struct {
	mock.Mock
}

// Err provides a mock function with given fields:
func (_m *mockStorageAccountListPager) Err() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NextPage provides a mock function with given fields: ctx
func (_m *mockStorageAccountListPager) NextPage(ctx context.Context) bool {
	ret := _m.Called(ctx)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// PageResponse provides a mock function with given fields:
func (_m *mockStorageAccountListPager) PageResponse() armstorage.StorageAccountsListResponse {
	ret := _m.Called()

	var r0 armstorage.StorageAccountsListResponse
	if rf, ok := ret.Get(0).(func() armstorage.StorageAccountsListResponse); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(armstorage.StorageAccountsListResponse)
	}

	return r0
}

type mockConstructorTestingTnewMockStorageAccountListPager interface {
	mock.TestingT
	Cleanup(func())
}

// newMockStorageAccountListPager creates a new instance of mockStorageAccountListPager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockStorageAccountListPager(t mockConstructorTestingTnewMockStorageAccountListPager) *mockStorageAccountListPager {
	mock := &mockStorageAccountListPager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
