// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ProviderDownloaderInterface is an autogenerated mock type for the ProviderDownloaderInterface type
type ProviderDownloaderInterface struct {
	mock.Mock
}

// Download provides a mock function with given fields: url, path
func (_m *ProviderDownloaderInterface) Download(url string, path string) error {
	ret := _m.Called(url, path)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(url, path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetProviderUrl provides a mock function with given fields: name, version
func (_m *ProviderDownloaderInterface) GetProviderUrl(name string, version string) string {
	ret := _m.Called(name, version)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(name, version)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
