// Code generated by mockery v2.28.1. DO NOT EDIT.

package repository

import (
	elasticache "github.com/aws/aws-sdk-go/service/elasticache"
	mock "github.com/stretchr/testify/mock"
)

// MockElastiCacheRepository is an autogenerated mock type for the ElastiCacheRepository type
type MockElastiCacheRepository struct {
	mock.Mock
}

// ListAllCacheClusters provides a mock function with given fields:
func (_m *MockElastiCacheRepository) ListAllCacheClusters() ([]*elasticache.CacheCluster, error) {
	ret := _m.Called()

	var r0 []*elasticache.CacheCluster
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*elasticache.CacheCluster, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*elasticache.CacheCluster); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*elasticache.CacheCluster)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockElastiCacheRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockElastiCacheRepository creates a new instance of MockElastiCacheRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockElastiCacheRepository(t mockConstructorTestingTNewMockElastiCacheRepository) *MockElastiCacheRepository {
	mock := &MockElastiCacheRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
