// Code generated by mockery v2.28.1. DO NOT EDIT.

package repository

import (
	elbv2 "github.com/aws/aws-sdk-go/service/elbv2"
	mock "github.com/stretchr/testify/mock"
)

// MockELBV2Repository is an autogenerated mock type for the ELBV2Repository type
type MockELBV2Repository struct {
	mock.Mock
}

// ListAllLoadBalancerListeners provides a mock function with given fields: _a0
func (_m *MockELBV2Repository) ListAllLoadBalancerListeners(_a0 string) ([]*elbv2.Listener, error) {
	ret := _m.Called(_a0)

	var r0 []*elbv2.Listener
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*elbv2.Listener, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) []*elbv2.Listener); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*elbv2.Listener)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAllLoadBalancers provides a mock function with given fields:
func (_m *MockELBV2Repository) ListAllLoadBalancers() ([]*elbv2.LoadBalancer, error) {
	ret := _m.Called()

	var r0 []*elbv2.LoadBalancer
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*elbv2.LoadBalancer, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*elbv2.LoadBalancer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*elbv2.LoadBalancer)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockELBV2Repository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockELBV2Repository creates a new instance of MockELBV2Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockELBV2Repository(t mockConstructorTestingTNewMockELBV2Repository) *MockELBV2Repository {
	mock := &MockELBV2Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
