// Code generated by mockery v1.0.0. DO NOT EDIT.

package repository

import (
	"github.com/stretchr/testify/mock"

	"github.com/aws/aws-sdk-go/service/sns"
)

// MockSNSRepository is an autogenerated mock type for the MockSNSRepository type
type MockSNSRepository struct {
	mock.Mock
}

// ListAllSubscriptions provides a mock function with given fields:
func (_m *MockSNSRepository) ListAllSubscriptions() ([]*sns.Subscription, error) {
	ret := _m.Called()

	var r0 []*sns.Subscription
	if rf, ok := ret.Get(0).(func() []*sns.Subscription); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sns.Subscription)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAllTopics provides a mock function with given fields:
func (_m *MockSNSRepository) ListAllTopics() ([]*sns.Topic, error) {
	ret := _m.Called()

	var r0 []*sns.Topic
	if rf, ok := ret.Get(0).(func() []*sns.Topic); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sns.Topic)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
