// GENERATED, DO NOT EDIT THIS FILE
package github

import "github.com/snyk/driftctl/enumeration/resource"

const GithubMembershipResourceType = "github_membership"

func initGithubMembershipMetaData(resourceSchemaRepository resource.SchemaRepositoryInterface) {
	resourceSchemaRepository.SetFlags(GithubMembershipResourceType, resource.FlagDeepMode)
}
