@startuml
driftctl -> Scanner: Resource()
hnote across: Enumeration phase
Scanner -> Scanner: List Enumerators
loop
Scanner -> Enumerator: Enumerate()
Enumerator -> RemoteSDK: List resources
RemoteSDK --> Enumerator: []remoteRes
alt optionally retrieve resource needed attributes
Enumerator -> RemoteSDK: Retrieve needed attributes
RemoteSDK --> Enumerator: Attrs
end
Enumerator --> Scanner: []Resource with limited attributes
end
Scanner --> driftctl: []Resource
@enduml