// GENERATED, DO NOT EDIT THIS FILE
package github

import "github.com/cloudskiff/driftctl/pkg/resource"

const GithubMembershipResourceType = "github_membership"

func initGithubMembershipMetaData(resourceSchemaRepository resource.SchemaRepositoryInterface) {
	resourceSchemaRepository.SetNormalizeFunc(GithubMembershipResourceType, func(res *resource.AbstractResource) {
		val := res.Attrs
		val.SafeDelete([]string{"etag"})
	})
}
