// GENERATED, DO NOT EDIT THIS FILE
package github

import (
	"github.com/snyk/driftctl/enumeration/resource"
	"github.com/snyk/driftctl/enumeration/resource/github"
)

func initGithubTeamMetaData(resourceSchemaRepository resource.SchemaRepositoryInterface) {
	resourceSchemaRepository.SetNormalizeFunc(github.GithubTeamResourceType, func(res *resource.Resource) {
		val := res.Attrs
		if defaultMaintainer, exist := val.Get("create_default_maintainer"); !exist || defaultMaintainer == nil {
			(*val)["create_default_maintainer"] = false
		}
		val.SafeDelete([]string{"etag"})
	})
}
