// GENERATED, DO NOT EDIT THIS FILE
package github

const GithubTeamResourceType = "github_team"

type GithubTeam struct {
	CreateDefaultMaintainer *bool   `cty:"create_default_maintainer"`
	Description             *string `cty:"description"`
	Etag                    *string `cty:"etag" computed:"true" diff:"-"`
	Id                      string  `cty:"id" computed:"true"`
	LdapDn                  *string `cty:"ldap_dn"`
	MembersCount            *int    `cty:"members_count" computed:"true"`
	Name                    *string `cty:"name"`
	NodeId                  *string `cty:"node_id" computed:"true"`
	ParentTeamId            *int    `cty:"parent_team_id"`
	Privacy                 *string `cty:"privacy"`
	Slug                    *string `cty:"slug" computed:"true"`
}

func (r *GithubTeam) TerraformId() string {
	return r.Id
}

func (r *GithubTeam) TerraformType() string {
	return GithubTeamResourceType
}
