// GENERATED, DO NOT EDIT THIS FILE
package github

const GithubMembershipResourceType = "github_membership"

type GithubMembership struct {
	Etag     *string `cty:"etag" computed:"true" diff:"-"`
	Id       string  `cty:"id" computed:"true"`
	Role     *string `cty:"role"`
	Username *string `cty:"username"`
}

func (r *GithubMembership) TerraformId() string {
	return r.Id
}

func (r *GithubMembership) TerraformType() string {
	return GithubMembershipResourceType
}
