// GENERATED, DO NOT EDIT THIS FILE
package github

import (
	"github.com/zclconf/go-cty/cty"

	"github.com/cloudskiff/driftctl/pkg/dctlcty"
)

const GithubMembershipResourceType = "github_membership"

type GithubMembership struct {
	Etag     *string    `cty:"etag" computed:"true" diff:"-"`
	Id       string     `cty:"id" computed:"true"`
	Role     *string    `cty:"role"`
	Username *string    `cty:"username"`
	CtyVal   *cty.Value `diff:"-"`
}

func (r *GithubMembership) TerraformId() string {
	return r.Id
}

func (r *GithubMembership) TerraformType() string {
	return GithubMembershipResourceType
}

func (r *GithubMembership) CtyValue() *cty.Value {
	return r.CtyVal
}

func initGithubMembershipMetadata() {
	dctlcty.SetMetadata(GithubMembershipResourceType, GithubMembershipTags, GithubMembershipNormalizer)
}

var GithubMembershipTags = map[string]string{}

func GithubMembershipNormalizer(val *dctlcty.CtyAttributes) {
	val.SafeDelete([]string{"etag"})
}
