// GENERATED, DO NOT EDIT THIS FILE
package github

const GithubTeamMembershipResourceType = "github_team_membership"

type GithubTeamMembership struct {
	Etag     *string `cty:"etag" computed:"true" diff:"-"`
	Id       string  `cty:"id" computed:"true"`
	Role     *string `cty:"role"`
	TeamId   *string `cty:"team_id"`
	Username *string `cty:"username"`
}

func (r *GithubTeamMembership) TerraformId() string {
	return r.Id
}

func (r *GithubTeamMembership) TerraformType() string {
	return GithubTeamMembershipResourceType
}
