// GENERATED, DO NOT EDIT THIS FILE
package github

import (
	"github.com/snyk/driftctl/enumeration/resource"
	"github.com/snyk/driftctl/enumeration/resource/github"
)

func initGithubBranchProtectionMetaData(resourceSchemaRepository resource.SchemaRepositoryInterface) {
	resourceSchemaRepository.SetNormalizeFunc(github.GithubBranchProtectionResourceType, func(res *resource.Resource) {
		val := res.Attrs
		val.SafeDelete([]string{"repository_id"}) // Terraform provider is always returning nil
	})
}
