// GENERATED, DO NOT EDIT THIS FILE
package github

import (
	"github.com/zclconf/go-cty/cty"

	"github.com/cloudskiff/driftctl/pkg/dctlcty"
)

const GithubTeamResourceType = "github_team"

type GithubTeam struct {
	CreateDefaultMaintainer *bool      `cty:"create_default_maintainer"`
	Description             *string    `cty:"description"`
	Etag                    *string    `cty:"etag" computed:"true" diff:"-"`
	Id                      string     `cty:"id" computed:"true"`
	LdapDn                  *string    `cty:"ldap_dn"`
	MembersCount            *int       `cty:"members_count" computed:"true"`
	Name                    *string    `cty:"name"`
	NodeId                  *string    `cty:"node_id" computed:"true"`
	ParentTeamId            *int       `cty:"parent_team_id"`
	Privacy                 *string    `cty:"privacy"`
	Slug                    *string    `cty:"slug" computed:"true"`
	CtyVal                  *cty.Value `diff:"-"`
}

func (r *GithubTeam) TerraformId() string {
	return r.Id
}

func (r *GithubTeam) TerraformType() string {
	return GithubTeamResourceType
}

func (r *GithubTeam) CtyValue() *cty.Value {
	return r.CtyVal
}

func initGithubTeamMetadata() {
	dctlcty.SetMetadata(GithubTeamResourceType, GithubTeamTags, GithubTeamNormalizer)
}

var GithubTeamTags = map[string]string{}

func GithubTeamNormalizer(val *dctlcty.CtyAttributes) {
	val.SafeDelete([]string{"etag"})
}
