// GENERATED, DO NOT EDIT THIS FILE
package aws

import (
	"github.com/zclconf/go-cty/cty"

	"github.com/cloudskiff/driftctl/pkg/dctlcty"
)

const AwsDbSubnetGroupResourceType = "aws_db_subnet_group"

type AwsDbSubnetGroup struct {
	Arn         *string           `cty:"arn" computed:"true"`
	Description *string           `cty:"description"`
	Id          string            `cty:"id" computed:"true"`
	Name        *string           `cty:"name" computed:"true"`
	NamePrefix  *string           `cty:"name_prefix" computed:"true" diff:"-"`
	SubnetIds   []string          `cty:"subnet_ids"`
	Tags        map[string]string `cty:"tags"`
	CtyVal      *cty.Value        `diff:"-"`
}

func (r *AwsDbSubnetGroup) TerraformId() string {
	return r.Id
}

func (r *AwsDbSubnetGroup) TerraformType() string {
	return AwsDbSubnetGroupResourceType
}

func (r *AwsDbSubnetGroup) CtyValue() *cty.Value {
	return r.CtyVal
}

var awsDbSubnetGroupTags = map[string]string{}

func awsDbSubnetGroupNormalizer(val *dctlcty.CtyAttributes) {
	val.SafeDelete([]string{"name_prefix"})
}
