// GENERATED, DO NOT EDIT THIS FILE
package aws

import (
	"github.com/zclconf/go-cty/cty"

	"github.com/cloudskiff/driftctl/pkg/helpers"
)

const AwsKmsAliasResourceType = "aws_kms_alias"

type AwsKmsAlias struct {
	Arn          *string    `cty:"arn" computed:"true"`
	Id           string     `cty:"id" computed:"true"`
	Name         *string    `cty:"name" diff:"-"`
	NamePrefix   *string    `cty:"name_prefix" diff:"-"`
	TargetKeyArn *string    `cty:"target_key_arn" computed:"true"`
	TargetKeyId  *string    `cty:"target_key_id"`
	CtyVal       *cty.Value `diff:"-"`
}

func (r *AwsKmsAlias) TerraformId() string {
	return r.Id
}

func (r *AwsKmsAlias) TerraformType() string {
	return AwsKmsAliasResourceType
}

func (r *AwsKmsAlias) CtyValue() *cty.Value {
	return r.CtyVal
}

func awsKmsAliasNormalizer(val *map[string]interface{}) {
	helpers.SafeDelete(val, []string{"name"})
	helpers.SafeDelete(val, []string{"name_prefix"})
}
