// GENERATED, DO NOT EDIT THIS FILE
package aws

import (
	"github.com/zclconf/go-cty/cty"

	"github.com/cloudskiff/driftctl/pkg/dctlcty"
)

const AwsS3BucketNotificationResourceType = "aws_s3_bucket_notification"

type AwsS3BucketNotification struct {
	Bucket         *string `cty:"bucket" diff:"-"`
	Id             string  `cty:"id" diff:"-" computed:"true"`
	LambdaFunction *[]struct {
		Events            []string `cty:"events"`
		FilterPrefix      *string  `cty:"filter_prefix"`
		FilterSuffix      *string  `cty:"filter_suffix"`
		Id                string   `cty:"id" computed:"true"`
		LambdaFunctionArn *string  `cty:"lambda_function_arn"`
	} `cty:"lambda_function"`
	Queue *[]struct {
		Events       []string `cty:"events"`
		FilterPrefix *string  `cty:"filter_prefix"`
		FilterSuffix *string  `cty:"filter_suffix"`
		Id           string   `cty:"id" computed:"true"`
		QueueArn     *string  `cty:"queue_arn"`
	} `cty:"queue"`
	Topic *[]struct {
		Events       []string `cty:"events"`
		FilterPrefix *string  `cty:"filter_prefix"`
		FilterSuffix *string  `cty:"filter_suffix"`
		Id           string   `cty:"id" computed:"true"`
		TopicArn     *string  `cty:"topic_arn"`
	} `cty:"topic"`
	CtyVal *cty.Value `diff:"-"`
}

func (r *AwsS3BucketNotification) TerraformId() string {
	return r.Id
}

func (r *AwsS3BucketNotification) TerraformType() string {
	return AwsS3BucketNotificationResourceType
}

func (r *AwsS3BucketNotification) CtyValue() *cty.Value {
	return r.CtyVal
}

func initAwsS3BucketNotificationMetaData() {
	dctlcty.SetMetadata(AwsS3BucketNotificationResourceType, AwsS3BucketNotificationTags, AwsS3BucketNotificationNormalizer)
}

var AwsS3BucketNotificationTags = map[string]string{
	"id":                 `computed:"true"`,
	"lambda_function.id": `computed:"true"`,
	"queue.id":           `computed:"true"`,
	"topic.id":           `computed:"true"`,
}

func AwsS3BucketNotificationNormalizer(val *dctlcty.CtyAttributes) {
	val.SafeDelete([]string{"id"})
	val.SafeDelete([]string{"bucket"})
}
