// GENERATED, DO NOT EDIT THIS FILE
package aws

import (
	"github.com/zclconf/go-cty/cty"

	"github.com/cloudskiff/driftctl/pkg/dctlcty"
)

const AwsIamUserPolicyResourceType = "aws_iam_user_policy"

type AwsIamUserPolicy struct {
	Id         string     `cty:"id" computed:"true"`
	Name       *string    `cty:"name" computed:"true"`
	NamePrefix *string    `cty:"name_prefix"`
	Policy     *string    `cty:"policy" jsonstring:"true"`
	User       *string    `cty:"user"`
	CtyVal     *cty.Value `diff:"-"`
}

func (r *AwsIamUserPolicy) TerraformId() string {
	return r.Id
}

func (r *AwsIamUserPolicy) TerraformType() string {
	return AwsIamUserPolicyResourceType
}

func (r *AwsIamUserPolicy) CtyValue() *cty.Value {
	return r.CtyVal
}

func initAwsIamUserPolicyMetaData() {
	dctlcty.SetMetadata(AwsIamUserPolicyResourceType, AwsIamUserPolicyTags, AwsIamUserPolicyNormalizer)
}

var AwsIamUserPolicyTags = map[string]string{
	"id":     `computed:"true"`,
	"name":   `computed:"true"`,
	"policy": `jsonstring:"true"`,
}

func AwsIamUserPolicyNormalizer(val *dctlcty.CtyAttributes) {
}
