// GENERATED, DO NOT EDIT THIS FILE
package aws

const AwsEipAssociationResourceType = "aws_eip_association"

type AwsEipAssociation struct {
	AllocationId       *string `cty:"allocation_id" computed:"true"`
	AllowReassociation *bool   `cty:"allow_reassociation"`
	Id                 string  `cty:"id" computed:"true"`
	InstanceId         *string `cty:"instance_id" computed:"true"`
	NetworkInterfaceId *string `cty:"network_interface_id" computed:"true"`
	PrivateIpAddress   *string `cty:"private_ip_address" computed:"true"`
	PublicIp           *string `cty:"public_ip" computed:"true"`
}

func (r *AwsEipAssociation) TerraformId() string {
	return r.Id
}

func (r *AwsEipAssociation) TerraformType() string {
	return AwsEipAssociationResourceType
}
