// GENERATED, DO NOT EDIT THIS FILE
package aws

const AwsIamUserResourceType = "aws_iam_user"

type AwsIamUser struct {
	Arn                 *string           `cty:"arn" computed:"true"`
	ForceDestroy        *bool             `cty:"force_destroy" diff:"-"`
	Id                  string            `cty:"id" computed:"true"`
	Name                *string           `cty:"name"`
	Path                *string           `cty:"path"`
	PermissionsBoundary *string           `cty:"permissions_boundary"`
	Tags                map[string]string `cty:"tags"`
	UniqueId            *string           `cty:"unique_id" computed:"true"`
}

func (r *AwsIamUser) TerraformId() string {
	return r.Id
}

func (r *AwsIamUser) TerraformType() string {
	return AwsIamUserResourceType
}
