// GENERATED, DO NOT EDIT THIS FILE
package aws

import (
	"github.com/zclconf/go-cty/cty"

	"github.com/cloudskiff/driftctl/pkg/dctlcty"
)

const AwsS3BucketPolicyResourceType = "aws_s3_bucket_policy"

type AwsS3BucketPolicy struct {
	Bucket *string    `cty:"bucket" diff:"-"`
	Id     string     `cty:"id" diff:"-" computed:"true"`
	Policy *string    `cty:"policy" jsonstring:"true"`
	CtyVal *cty.Value `diff:"-"`
}

func (r *AwsS3BucketPolicy) TerraformId() string {
	return r.Id
}

func (r *AwsS3BucketPolicy) TerraformType() string {
	return AwsS3BucketPolicyResourceType
}

func (r *AwsS3BucketPolicy) CtyValue() *cty.Value {
	return r.CtyVal
}

func initAwsS3BucketPolicyMetaData() {
	dctlcty.SetMetadata(AwsS3BucketPolicyResourceType, AwsS3BucketPolicyTags, AwsS3BucketPolicyNormalizer)
}

var AwsS3BucketPolicyTags = map[string]string{
	"id":     `computed:"true"`,
	"policy": `jsonstring:"true"`,
}

func AwsS3BucketPolicyNormalizer(val *dctlcty.CtyAttributes) {
	val.SafeDelete([]string{"bucket"})
	val.SafeDelete([]string{"id"})
}
