// GENERATED, DO NOT EDIT THIS FILE
package aws

const AwsS3BucketInventoryResourceType = "aws_s3_bucket_inventory"

type AwsS3BucketInventory struct {
	Bucket                 *string  `cty:"bucket"`
	Enabled                *bool    `cty:"enabled"`
	Id                     string   `cty:"id" computed:"true"`
	IncludedObjectVersions *string  `cty:"included_object_versions"`
	Name                   *string  `cty:"name"`
	OptionalFields         []string `cty:"optional_fields"`
	Destination            *[]struct {
		Bucket *[]struct {
			AccountId  *string `cty:"account_id"`
			BucketArn  *string `cty:"bucket_arn"`
			Format     *string `cty:"format"`
			Prefix     *string `cty:"prefix"`
			Encryption *[]struct {
				SseKms *[]struct {
					KeyId *string `cty:"key_id"`
				} `cty:"sse_kms"`
				SseS3 []struct {
				} `cty:"sse_s3"`
			} `cty:"encryption"`
		} `cty:"bucket"`
	} `cty:"destination"`
	Filter *[]struct {
		Prefix *string `cty:"prefix"`
	} `cty:"filter"`
	Schedule *[]struct {
		Frequency *string `cty:"frequency"`
	} `cty:"schedule"`
}

func (r *AwsS3BucketInventory) TerraformId() string {
	return r.Id
}

func (r *AwsS3BucketInventory) TerraformType() string {
	return AwsS3BucketInventoryResourceType
}
