// GENERATED, DO NOT EDIT THIS FILE
package aws

import "github.com/zclconf/go-cty/cty"

const AwsS3BucketAnalyticsConfigurationResourceType = "aws_s3_bucket_analytics_configuration"

type AwsS3BucketAnalyticsConfiguration struct {
	Bucket *string `cty:"bucket"`
	Id     string  `cty:"id" computed:"true"`
	Name   *string `cty:"name"`
	Filter *[]struct {
		Prefix *string           `cty:"prefix"`
		Tags   map[string]string `cty:"tags"`
	} `cty:"filter"`
	StorageClassAnalysis *[]struct {
		DataExport *[]struct {
			OutputSchemaVersion *string `cty:"output_schema_version"`
			Destination         *[]struct {
				S3BucketDestination *[]struct {
					BucketAccountId *string `cty:"bucket_account_id"`
					BucketArn       *string `cty:"bucket_arn"`
					Format          *string `cty:"format"`
					Prefix          *string `cty:"prefix"`
				} `cty:"s3_bucket_destination"`
			} `cty:"destination"`
		} `cty:"data_export"`
	} `cty:"storage_class_analysis"`
	CtyVal *cty.Value `diff:"-"`
}

func (r *AwsS3BucketAnalyticsConfiguration) TerraformId() string {
	return r.Id
}

func (r *AwsS3BucketAnalyticsConfiguration) TerraformType() string {
	return AwsS3BucketAnalyticsConfigurationResourceType
}

func (r *AwsS3BucketAnalyticsConfiguration) CtyValue() *cty.Value {
	return r.CtyVal
}
