// GENERATED, DO NOT EDIT THIS FILE
package aws

const AwsSnsTopicPolicyResourceType = "aws_sns_topic_policy"

type AwsSnsTopicPolicy struct {
	Arn    *string `cty:"arn"`
	Id     string  `cty:"id" computed:"true"`
	Policy *string `cty:"policy" jsonstring:"true"`
}

func (r *AwsSnsTopicPolicy) TerraformId() string {
	return r.Id
}

func (r *AwsSnsTopicPolicy) TerraformType() string {
	return AwsSnsTopicPolicyResourceType
}
