// GENERATED, DO NOT EDIT THIS FILE
package aws

const AwsSnsTopicResourceType = "aws_sns_topic"

type AwsSnsTopic struct {
	ApplicationFailureFeedbackRoleArn    *string           `cty:"application_failure_feedback_role_arn"`
	ApplicationSuccessFeedbackRoleArn    *string           `cty:"application_success_feedback_role_arn"`
	ApplicationSuccessFeedbackSampleRate *int              `cty:"application_success_feedback_sample_rate"`
	Arn                                  *string           `cty:"arn" computed:"true"`
	DeliveryPolicy                       *string           `cty:"delivery_policy"`
	DisplayName                          *string           `cty:"display_name"`
	HttpFailureFeedbackRoleArn           *string           `cty:"http_failure_feedback_role_arn"`
	HttpSuccessFeedbackRoleArn           *string           `cty:"http_success_feedback_role_arn"`
	HttpSuccessFeedbackSampleRate        *int              `cty:"http_success_feedback_sample_rate"`
	Id                                   string            `cty:"id" computed:"true"`
	KmsMasterKeyId                       *string           `cty:"kms_master_key_id"`
	LambdaFailureFeedbackRoleArn         *string           `cty:"lambda_failure_feedback_role_arn"`
	LambdaSuccessFeedbackRoleArn         *string           `cty:"lambda_success_feedback_role_arn"`
	LambdaSuccessFeedbackSampleRate      *int              `cty:"lambda_success_feedback_sample_rate"`
	Name                                 *string           `cty:"name" computed:"true"`
	NamePrefix                           *string           `cty:"name_prefix"`
	Policy                               *string           `cty:"policy" computed:"true"`
	SqsFailureFeedbackRoleArn            *string           `cty:"sqs_failure_feedback_role_arn"`
	SqsSuccessFeedbackRoleArn            *string           `cty:"sqs_success_feedback_role_arn"`
	SqsSuccessFeedbackSampleRate         *int              `cty:"sqs_success_feedback_sample_rate"`
	Tags                                 map[string]string `cty:"tags"`
}

func (r *AwsSnsTopic) TerraformId() string {
	return r.Id
}

func (r *AwsSnsTopic) TerraformType() string {
	return AwsSnsTopicResourceType
}
