// GENERATED, DO NOT EDIT THIS FILE
package aws

import (
	"github.com/zclconf/go-cty/cty"

	"github.com/cloudskiff/driftctl/pkg/dctlcty"
)

const AwsIamRolePolicyResourceType = "aws_iam_role_policy"

type AwsIamRolePolicy struct {
	Id         string     `cty:"id" computed:"true"`
	Name       *string    `cty:"name" computed:"true"`
	NamePrefix *string    `cty:"name_prefix"`
	Policy     *string    `cty:"policy" jsonstring:"true"`
	Role       *string    `cty:"role"`
	CtyVal     *cty.Value `diff:"-"`
}

func (r *AwsIamRolePolicy) TerraformId() string {
	return r.Id
}

func (r *AwsIamRolePolicy) TerraformType() string {
	return AwsIamRolePolicyResourceType
}

func (r *AwsIamRolePolicy) CtyValue() *cty.Value {
	return r.CtyVal
}

func initAwsIamRolePolicyMetaData() {
	dctlcty.SetMetadata(AwsIamRolePolicyResourceType, AwsIamRolePolicyTags, AwsIamRolePolicyNormalizer)
}

var AwsIamRolePolicyTags = map[string]string{
	"id":     `computed:"true"`,
	"name":   `computed:"true"`,
	"policy": `jsonstring:"true"`,
}

func AwsIamRolePolicyNormalizer(val *dctlcty.CtyAttributes) {
}
