// Code generated by mockery v1.0.0. DO NOT EDIT.

package repository

import (
	apigateway "github.com/aws/aws-sdk-go/service/apigateway"
	mock "github.com/stretchr/testify/mock"
)

// MockApiGatewayRepository is an autogenerated mock type for the ApiGatewayRepository type
type MockApiGatewayRepository struct {
	mock.Mock
}

// ListAllRestApis provides a mock function with given fields:
func (_m *MockApiGatewayRepository) ListAllRestApis() ([]*apigateway.RestApi, error) {
	ret := _m.Called()

	var r0 []*apigateway.RestApi
	if rf, ok := ret.Get(0).(func() []*apigateway.RestApi); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*apigateway.RestApi)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
