// Code generated by mockery v1.0.0. DO NOT EDIT.

package repository

import (
	"github.com/aws/aws-sdk-go/service/cloudfront"
	"github.com/stretchr/testify/mock"
)

// MockCloudfrontRepository is an autogenerated mock type for the MockCloudfrontRepository type
type MockCloudfrontRepository struct {
	mock.Mock
}

// ListAllDistributions provides a mock function with given fields:
func (_m *MockCloudfrontRepository) ListAllDistributions() ([]*cloudfront.DistributionSummary, error) {
	ret := _m.Called()

	var r0 []*cloudfront.DistributionSummary
	if rf, ok := ret.Get(0).(func() []*cloudfront.DistributionSummary); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*cloudfront.DistributionSummary)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
