// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package repository

import (
	context "context"

	armprivatedns "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/privatedns/armprivatedns"

	mock "github.com/stretchr/testify/mock"
)

// mockPrivateDNSRecordSetListPager is an autogenerated mock type for the privateDNSRecordSetListPager type
type mockPrivateDNSRecordSetListPager struct {
	mock.Mock
}

// Err provides a mock function with given fields:
func (_m *mockPrivateDNSRecordSetListPager) Err() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NextPage provides a mock function with given fields: ctx
func (_m *mockPrivateDNSRecordSetListPager) NextPage(ctx context.Context) bool {
	ret := _m.Called(ctx)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// PageResponse provides a mock function with given fields:
func (_m *mockPrivateDNSRecordSetListPager) PageResponse() armprivatedns.RecordSetsListResponse {
	ret := _m.Called()

	var r0 armprivatedns.RecordSetsListResponse
	if rf, ok := ret.Get(0).(func() armprivatedns.RecordSetsListResponse); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(armprivatedns.RecordSetsListResponse)
	}

	return r0
}
