// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package repository

import (
	context "context"

	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage"

	mock "github.com/stretchr/testify/mock"
)

// mockBlobContainerListPager is an autogenerated mock type for the blobContainerListPager type
type mockBlobContainerListPager struct {
	mock.Mock
}

// Err provides a mock function with given fields:
func (_m *mockBlobContainerListPager) Err() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NextPage provides a mock function with given fields: ctx
func (_m *mockBlobContainerListPager) NextPage(ctx context.Context) bool {
	ret := _m.Called(ctx)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// PageResponse provides a mock function with given fields:
func (_m *mockBlobContainerListPager) PageResponse() armstorage.BlobContainersListResponse {
	ret := _m.Called()

	var r0 armstorage.BlobContainersListResponse
	if rf, ok := ret.Get(0).(func() armstorage.BlobContainersListResponse); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(armstorage.BlobContainersListResponse)
	}

	return r0
}
