// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package repository

import (
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage"
	mock "github.com/stretchr/testify/mock"
)

// mockBlobContainerClient is an autogenerated mock type for the blobContainerClient type
type mockBlobContainerClient struct {
	mock.Mock
}

// List provides a mock function with given fields: resourceGroupName, accountName, options
func (_m *mockBlobContainerClient) List(resourceGroupName string, accountName string, options *armstorage.BlobContainersListOptions) blobContainerListPager {
	ret := _m.Called(resourceGroupName, accountName, options)

	var r0 blobContainerListPager
	if rf, ok := ret.Get(0).(func(string, string, *armstorage.BlobContainersListOptions) blobContainerListPager); ok {
		r0 = rf(resourceGroupName, accountName, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(blobContainerListPager)
		}
	}

	return r0
}
