// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package repository

import (
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armresources"
	mock "github.com/stretchr/testify/mock"
)

// MockResourcesRepository is an autogenerated mock type for the ResourcesRepository type
type MockResourcesRepository struct {
	mock.Mock
}

// ListAllResourceGroups provides a mock function with given fields:
func (_m *MockResourcesRepository) ListAllResourceGroups() ([]*armresources.ResourceGroup, error) {
	ret := _m.Called()

	var r0 []*armresources.ResourceGroup
	if rf, ok := ret.Get(0).(func() []*armresources.ResourceGroup); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*armresources.ResourceGroup)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
