// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package repository

import (
	armprivatedns "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/privatedns/armprivatedns"
	mock "github.com/stretchr/testify/mock"
)

// mockPrivateZonesClient is an autogenerated mock type for the privateZonesClient type
type mockPrivateZonesClient struct {
	mock.Mock
}

// List provides a mock function with given fields: options
func (_m *mockPrivateZonesClient) List(options *armprivatedns.PrivateZonesListOptions) privateDNSZoneListPager {
	ret := _m.Called(options)

	var r0 privateDNSZoneListPager
	if rf, ok := ret.Get(0).(func(*armprivatedns.PrivateZonesListOptions) privateDNSZoneListPager); ok {
		r0 = rf(options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(privateDNSZoneListPager)
		}
	}

	return r0
}
